apiVersion: v1
kind: ConfigMap
metadata:
  name: deal
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/neostudy"
  CALCULATOR_SERVICE_HOST: "calculator:8080"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
