version: '3.8'
services:
  calculator-app:
    container_name: calculator-container
    build:
      context: ./calculator
    ports:
      - "8080:8080"
  deal-app:
    container_name: deal-container
    build:
      context: ./deal
    ports:
      - "8081:8080"