version: '3.8'
services:
  calculator-app:
    container_name: calculator-container
    build:
      context: ./calculator
    ports:
      - "8080:8080"
  deal-app:
    container_name: deal-container
    env_file:
      - .env
    build:
      context: ./deal
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      CALCULATOR_SERVICE_HOST: ${CALCULATOR_SERVICE_HOST}
      SERVER_PORT: 8081
