apiVersion: apps/v1
kind: Deployment
metadata:
  name: dossier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dossier
  template:
    metadata:
      name: dossier
      labels:
        app: dossier
    spec:
      containers:
        - name: dossier
          image: dossier:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DEAL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: dossier
                  key: DEAL_SERVICE_HOST
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: dossier
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: APP_DEFAULT_LOCALE
              valueFrom:
                configMapKeyRef:
                  name: dossier
                  key: APP_DEFAULT_LOCALE
            - name: APP_MESSAGE_SEND_SES_BASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: dossier
                  key: APP_MESSAGE_SEND_SES_BASE_PATH
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: dossier
                  key: SPRING_MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: dossier
                  key: SPRING_MAIL_PORT
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dossier
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dossier
                  key: SPRING_MAIL_PASSWORD
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              valueFrom:
                secretKeyRef:
                  name: dossier
                  key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              valueFrom:
                secretKeyRef:
                  name: dossier
                  key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED
              valueFrom:
                secretKeyRef:
                  name: dossier
                  key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED
            - name: APP_CLIENT_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: deal
                  key: APP_SECURITY_AUTH_TOKEN
      restartPolicy: Always